include:
  - project: operations/pipeline
    ref: master
    file: default-maven-build.gitlab-ci.yml
  - project: operations/pipeline
    ref: master
    file: maven-publish.gitlab-ci.yml

build:
  image: maven:3.8.1-openjdk-17
  after_script:
    - awk -F"," '{ total+=$4+$5; covered+=$5 } END { print "Jacoco instructions covered", 100*covered/total, "%" }' target/site/jacoco/jacoco.csv
    - awk -F"," '{ total+=$6+$7; covered+=$7 } END { print "Jacoco branches covered", 100*covered/total, "%" }' target/site/jacoco/jacoco.csv
    - awk -F"," '{ total+=$8+$9; covered+=$9 } END { print "Jacoco lines covered", 100*covered/total, "%" }' target/site/jacoco/jacoco.csv
  coverage: /Jacoco instructions covered (\d+\.?\d*) %/
  artifacts:
    when: always
    paths: []
    reports:
      junit:
        - 'target/surefire-reports/TEST-*.xml'
        - 'target/failsafe-reports/TEST-*.xml'
